"""OpenMM helpers for the peptide self-assembly notebook."""

import os
from pathlib import Path
from typing import Union


import pandas as pd
from IPython.display import HTML, display
import re

import py3Dmol
import subprocess

import ipywidgets as widgets
import matplotlib.pyplot as plt

from openmm import Platform, VerletIntegrator, unit
from openmm.app import ForceField, NoCutoff, PDBFile, Simulation


# Consistent Martini 2.2 space-filling convention: half the like-bead LJ sigma.
# py3Dmol reads GRO/PDB coordinates in angstroms. These are illustrative
# radii, not hard-sphere boundaries (Martini interactions are pair-dependent).
PEPTIDE_BEAD_RADIUS_ANGSTROM = 2.35       # regular: sigma = 0.47 nm
SMALL_PEPTIDE_BEAD_RADIUS_ANGSTROM = 2.15  # S bead: sigma = 0.43 nm
WATER_BEAD_RADIUS_ANGSTROM = 2.35         # P4 water: sigma = 0.47 nm


def _peptide_bead_radius(bead_type):
    """Return a consistent display radius for a Martini 2.2 peptide bead."""
    if str(bead_type).startswith('S'):
        return SMALL_PEPTIDE_BEAD_RADIUS_ANGSTROM
    return PEPTIDE_BEAD_RADIUS_ANGSTROM


def minimize_peptides(coord_dir: Union[str, Path]) -> list[Path]:
    """Energy-minimize the 20 VMD-built Tyr-X-Tyr peptide structures.

    Each ``TYR-*-TYR_aa.pdb`` file in ``coord_dir`` is minimized on the
    OpenMM CPU platform with CHARMM36 and OBC2 implicit solvent. The minimized
    coordinates overwrite the input PDB file, matching the notebook workflow.

    Parameters
    ----------
    coord_dir
        Directory containing the PDB files generated by ``make_peptides.sh``.

    Returns
    -------
    list[pathlib.Path]
        The 20 minimized PDB paths, sorted by filename.
    """
    coord_dir = Path(coord_dir)
    generated = sorted(coord_dir.glob("TYR-*-TYR_aa.pdb"))
    assert len(generated) == 20, "Run make_peptides.sh before minimizing."

    forcefield = ForceField("charmm36.xml", "implicit/obc2.xml")
    platform = Platform.getPlatformByName("CPU")

    for pdb_file in generated:
        pdb = PDBFile(str(pdb_file))
        system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff)
        integrator = VerletIntegrator(0.001 * unit.picoseconds)
        simulation = Simulation(pdb.topology, system, integrator, platform)
        simulation.context.setPositions(pdb.positions)

        before = simulation.context.getState(getEnergy=True).getPotentialEnergy()
        simulation.minimizeEnergy(
            tolerance=10 * unit.kilojoule_per_mole / unit.nanometer,
            maxIterations=500,
        )
        state = simulation.context.getState(getEnergy=True, getPositions=True)
        after = state.getPotentialEnergy()

        with pdb_file.open("w") as output:
            PDBFile.writeFile(
                pdb.topology,
                state.getPositions(),
                output,
                keepIds=True,
            )

        before_kj_mol = before.value_in_unit(unit.kilojoule_per_mole)
        after_kj_mol = after.value_in_unit(unit.kilojoule_per_mole)
        print(f"{pdb_file.name}: {before_kj_mol:.1f} kJ/mol -> "
              f"{after_kj_mol:.1f} kJ/mol")

    return generated


def show_peptide(
    peptide: str,
    style: str,
    coord_dir: Union[str, Path],
) -> None:
    """Display a minimized peptide in an interactive py3Dmol viewer."""
    pdb_file = Path(coord_dir) / f"{peptide}_aa.pdb"
    if not pdb_file.is_file():
        raise FileNotFoundError(pdb_file)

    styles = {
        "Stick": {"stick": {"colorscheme": "Jmol"}},
        "Ball and stick": {
            "stick": {"colorscheme": "Jmol"},
            "sphere": {"scale": 0.3, "colorscheme": "Jmol"},
        },
        "Sphere": {"sphere": {"colorscheme": "Jmol"}},
    }
    if style not in styles:
        raise ValueError(f"Unknown style: {style!r}. Choose from {tuple(styles)}.")

    view = py3Dmol.view(width=800, height=500)
    view.addModel(pdb_file.read_text(), "pdb")
    view.setStyle({}, styles[style])
    view.setBackgroundColor("white")
    view.zoomTo()
    view.show()




def show_peptide_widget(generated, coord_dir: Union[str, Path]):
    """Create peptide and rendering-style controls for ``show_peptide``."""
    from ipywidgets import Dropdown, fixed, interact

    peptide_names = [
        path.name.removesuffix("_aa.pdb") for path in generated
    ]
    if not peptide_names:
        raise ValueError("No generated peptide files were provided.")

    default_peptide = (
        "TYR-VAL-TYR" if "TYR-VAL-TYR" in peptide_names else peptide_names[0]
    )

    return interact(
        show_peptide,
        peptide=Dropdown(
            options=peptide_names,
            value=default_peptide,
            description="Peptide:",
        ),
        style=Dropdown(
            options=["Stick", "Ball and stick", "Sphere"],
            value="Ball and stick",
            description="Style:",
        ),
        coord_dir=fixed(Path(coord_dir)),
    )



def show_peptide_comparison(peptide, cg_dir):
    """Compare an all-atom peptide with its Martini representation."""

    cg_dir = Path(cg_dir)

    aa_file = (
        cg_dir.parent
        / "2_Creating_coordinates"
        / f"{peptide}_aa.pdb"
    )
    cg_file = cg_dir / f"{peptide}.pdb"
    itp_file = cg_dir / f"{peptide}.itp"

    assert aa_file.is_file(), f"File not found: {aa_file}"
    assert cg_file.is_file(), f"File not found: {cg_file}"
    assert itp_file.is_file(), f"File not found: {itp_file}"

    itp_text = itp_file.read_text()

    # Read the coarse-grained coordinates from the PDB file.
    coordinates = {}

    for line in cg_file.read_text().splitlines():
        if line.startswith(("ATOM  ", "HETATM")):
            serial = int(line[6:11])

            coordinates[serial] = tuple(
                float(line[start:end])
                for start, end in (
                    (30, 38),
                    (38, 46),
                    (46, 54),
                )
            )

    family_names = {
        "Q": "charged",
        "P": "polar",
        "N": "intermediate",
        "C": "apolar",
    }

    family_colors = {
        "Q": "#D62728",
        "P": "#FF7F0E",
        "N": "#4169E1",
        "C": "#8A8A8A",
    }

    def bead_family(bead_type):
        core = bead_type[1:] if bead_type.startswith("S") else bead_type
        core = core[1:] if core.startswith("A") else core
        return core[0]

    def polarity_label(bead_type):
        core = bead_type[1:] if bead_type.startswith("S") else bead_type
        core = core[1:] if core.startswith("A") else core
        subtype = core[1:]

        h_bond = {
            "da": "donor + acceptor",
            "d": "donor",
            "a": "acceptor",
            "0": "none",
        }

        return h_bond.get(subtype, f"level {subtype}")

    # Read the bead information and connectivity from the topology.
    rows = []
    bond_pairs = []
    section = None

    for line in itp_text.splitlines():
        stripped = line.strip()

        if stripped.startswith("["):
            section = stripped.strip("[] ").lower()
            continue

        fields = line.split(";", 1)[0].split()

        if section == "atoms" and fields and fields[0].isdigit():
            index = int(fields[0])
            bead_type = fields[1]
            family = bead_family(bead_type)

            rows.append({
                "index": index,
                "residue": f"{fields[3]} {fields[2]}",
                "bead": fields[4],
                "Martini type": bead_type,
                "class": family_names[family],
                "polarity / H-bonding": polarity_label(bead_type),
                "charge (e)": float(fields[6]),
            })

        elif (
            section in ("bonds", "constraints")
            and len(fields) >= 2
            and fields[0].isdigit()
        ):
            bond_pairs.append((
                int(fields[0]),
                int(fields[1]),
            ))

    bead_table = (
        pd.DataFrame(rows)
        .sort_values("index")
        .reset_index(drop=True)
    )

    # Display only the requested columns.
    table_columns = [
        "residue",
        "bead",
        "Martini type",
        "class",
        "polarity / H-bonding",
    ]

    display(bead_table[table_columns].style.hide(axis="index"))

    print(
        "Color key: charged=red, polar=orange, "
        "intermediate=blue, apolar=gray."
    )
    print(
        "Connectivity:",
        ", ".join(f"{first}-{second}" for first, second in bond_pairs),
    )

    # Add titles above the molecular viewers.
    display(HTML(
        f"""
        <div style="display:flex; width:1000px; text-align:center">
            <b style="width:50%">All-atom: {peptide}</b>
            <b style="width:50%">Martini 2.2 beads</b>
        </div>
        """
    ))

    # Create two linked molecular viewers.
    view = py3Dmol.view(
        width=1000,
        height=520,
        viewergrid=(1, 2),
        linked=True,
    )

    # All-atom structure.
    view.addModel(
        aa_file.read_text(),
        "pdb",
        viewer=(0, 0),
    )

    view.setStyle(
        {},
        {
            "stick": {"colorscheme": "Jmol"},
            "sphere": {
                "scale": 0.25,
                "colorscheme": "Jmol",
            },
        },
        viewer=(0, 0),
    )

    # Martini coarse-grained structure.
    view.addModel(
        cg_file.read_text(),
        "pdb",
        viewer=(0, 1),
    )

    for row in rows:
        serial = row["index"]
        bead_type = row["Martini type"]
        color = family_colors[bead_family(bead_type)]

        view.setStyle(
            {"serial": serial},
            {
                "sphere": {
                    "color": color,
                    "radius": 1.1,
                }
            },
            viewer=(0, 1),
        )

        x, y, z = coordinates[serial]

        view.addLabel(
            (
                f"{row['bead']} | {bead_type} | "
                f"q={row['charge (e)']:+.0f}"
            ),
            {
                "position": {"x": x, "y": y, "z": z},
                "fontSize": 11,
                "fontColor": "black",
                "backgroundColor": "white",
                "backgroundOpacity": 0.75,
                "inFront": True,
            },
            viewer=(0, 1),
        )

    # Draw connections between Martini beads.
    for first, second in bond_pairs:
        start = coordinates[first]
        end = coordinates[second]

        view.addCylinder(
            {
                "start": dict(zip(("x", "y", "z"), start)),
                "end": dict(zip(("x", "y", "z"), end)),
                "radius": 0.12,
                "color": "#555555",
                "opacity": 0.75,
            },
            viewer=(0, 1),
        )

    view.setBackgroundColor("white")
    view.zoomTo()
    view.show()

    return bead_table

def visualize_inserted_peptides(box_file, bead_table, peptide, n_peptides):
    """Display the inserted peptides using the Martini bead-class colors."""
    gro_text = box_file.read_text()
    box_nm = [float(value) for value in gro_text.splitlines()[-1].split()[:3]]
    lx, ly, lz = [10.0 * value for value in box_nm]  # py3Dmol uses angstroms

    martini_colors = {
        'charged': 'red',
        'polar': 'orange',
        'intermediate': 'blue',
        'apolar': 'gray',
    }

    view = py3Dmol.view(width=800, height=600)
    view.addModel(gro_text, 'gro')
    view.setStyle({}, {
        'stick': {'radius': 0.12, 'color': 'gray'},
        'sphere': {'radius': PEPTIDE_BEAD_RADIUS_ANGSTROM, 'color': 'gray'},
    })

    # Apply the class color from bead_table to every copy of each bead.
    for _, bead in bead_table.iterrows():
        residue_name = bead['residue'].split()[0]
        color = martini_colors[bead['class']]
        view.setStyle(
            {'resn': residue_name, 'atom': bead['bead']},
            {
                'stick': {'radius': 0.12, 'color': color},
                'sphere': {
                    'radius': _peptide_bead_radius(bead['Martini type']),
                    'color': color,
                },
            },
        )

    # Draw the 12 edges of the periodic box.
    corners = [
        (0, 0, 0), (lx, 0, 0), (0, ly, 0), (lx, ly, 0),
        (0, 0, lz), (lx, 0, lz), (0, ly, lz), (lx, ly, lz),
    ]
    edges = [
        (0, 1), (0, 2), (1, 3), (2, 3),
        (4, 5), (4, 6), (5, 7), (6, 7),
        (0, 4), (1, 5), (2, 6), (3, 7),
    ]
    for start, end in edges:
        x1, y1, z1 = corners[start]
        x2, y2, z2 = corners[end]
        view.addLine({
            'start': {'x': x1, 'y': y1, 'z': z1},
            'end': {'x': x2, 'y': y2, 'z': z2},
            'color': 'black',
            'linewidth': 2,
        })

    view.setBackgroundColor('white')
    view.zoomTo()
    print(
        f'{n_peptides} {peptide} molecules in a '
        f'{box_nm[0]:g} x {box_nm[1]:g} x {box_nm[2]:g} nm box'
    )
    print('Color key: charged=red, polar=orange, intermediate=blue, apolar=gray.')
    view.show()
    return view

def visualize_solvated_system(water_file, bead_table):
    """Display Martini water and peptides in the solvated simulation box."""
    solvated_text = water_file.read_text()
    solvated_lines = solvated_text.splitlines()
    water_beads = sum(
        line[5:10].strip() == 'W' for line in solvated_lines[2:-1]
    )
    box_nm = [float(value) for value in solvated_lines[-1].split()[:3]]
    lx, ly, lz = [10.0 * value for value in box_nm]  # py3Dmol uses angstroms

    martini_colors = {
        'charged': 'red',
        'polar': 'orange',
        'intermediate': 'blue',
        'apolar': 'gray',
    }

    view = py3Dmol.view(width=800, height=600)
    view.addModel(solvated_text, 'gro')
    view.setStyle({}, {})

    # Use the Martini P4 bead size; transparency keeps peptides visible.
    view.setStyle(
        {'resn': 'W'},
        {'sphere': {
            'radius': WATER_BEAD_RADIUS_ANGSTROM,
            'color': 'cyan',
            'opacity': 0.35,
        }},
    )

    # Keep the peptide beads in the same Martini class colors as bead_table.
    for _, bead in bead_table.iterrows():
        residue_name = bead['residue'].split()[0]
        color = martini_colors[bead['class']]
        view.setStyle(
            {'resn': residue_name, 'atom': bead['bead']},
            {
                'stick': {'radius': 0.12, 'color': color},
                'sphere': {
                    'radius': _peptide_bead_radius(bead['Martini type']),
                    'color': color,
                },
            },
        )

    # Draw the 12 edges of the periodic box.
    corners = [
        (0, 0, 0), (lx, 0, 0), (0, ly, 0), (lx, ly, 0),
        (0, 0, lz), (lx, 0, lz), (0, ly, lz), (lx, ly, lz),
    ]
    edges = [
        (0, 1), (0, 2), (1, 3), (2, 3),
        (4, 5), (4, 6), (5, 7), (6, 7),
        (0, 4), (1, 5), (2, 6), (3, 7),
    ]
    for start, end in edges:
        x1, y1, z1 = corners[start]
        x2, y2, z2 = corners[end]
        view.addLine({
            'start': {'x': x1, 'y': y1, 'z': z1},
            'end': {'x': x2, 'y': y2, 'z': z2},
            'color': 'black',
            'linewidth': 2,
        })

    view.setBackgroundColor('white')
    view.zoomTo()
    print(f'Added {water_beads} Martini water beads (cyan).')
    print(
        'Peptides retain the Martini class colors: '
        'charged=red, polar=orange, intermediate=blue, apolar=gray.'
    )
    view.show()
    return view

def visualize_counterions(water_file, bead_table, peptide):
    """Highlight counterions in the neutralized Martini system, when present."""
    neutralized_text = water_file.read_text()
    neutralized_lines = neutralized_text.splitlines()
    ion_counts = {
        ion: sum(line[5:10].strip() == ion for line in neutralized_lines[2:-1])
        for ion in ('NA+', 'CL-')
    }

    if sum(ion_counts.values()) == 0:
        print(f'No counterions were required for {peptide}; the system was already neutral.')
        return None

    box_nm = [float(value) for value in neutralized_lines[-1].split()[:3]]
    lx, ly, lz = [10.0 * value for value in box_nm]  # py3Dmol uses angstroms
    martini_colors = {
        'charged': 'red',
        'polar': 'orange',
        'intermediate': 'blue',
        'apolar': 'gray',
    }

    view = py3Dmol.view(width=800, height=600)
    view.addModel(neutralized_text, 'gro')
    view.setStyle({}, {})

    # Keep full-size Martini water translucent to reveal peptides and ions.
    view.setStyle(
        {'resn': 'W'},
        {'sphere': {
            'radius': WATER_BEAD_RADIUS_ANGSTROM,
            'color': 'cyan',
            'opacity': 0.12,
        }},
    )
    for _, bead in bead_table.iterrows():
        residue_name = bead['residue'].split()[0]
        color = martini_colors[bead['class']]
        view.setStyle(
            {'resn': residue_name, 'atom': bead['bead']},
            {
                'stick': {'radius': 0.08, 'color': color},
                'sphere': {
                    'radius': _peptide_bead_radius(bead['Martini type']),
                    'color': color,
                },
            },
        )

    # Make counterions large and easy to distinguish.
    ion_colors = {'NA+': 'purple', 'CL-': 'green'}
    for ion, color in ion_colors.items():
        view.setStyle(
            {'resn': ion},
            {'sphere': {'scale': 0.75, 'color': color}},
        )

    # Draw the 12 edges of the periodic box.
    corners = [
        (0, 0, 0), (lx, 0, 0), (0, ly, 0), (lx, ly, 0),
        (0, 0, lz), (lx, 0, lz), (0, ly, lz), (lx, ly, lz),
    ]
    edges = [
        (0, 1), (0, 2), (1, 3), (2, 3),
        (4, 5), (4, 6), (5, 7), (6, 7),
        (0, 4), (1, 5), (2, 6), (3, 7),
    ]
    for start, end in edges:
        x1, y1, z1 = corners[start]
        x2, y2, z2 = corners[end]
        view.addLine({
            'start': {'x': x1, 'y': y1, 'z': z1},
            'end': {'x': x2, 'y': y2, 'z': z2},
            'color': 'black',
            'linewidth': 2,
        })

    view.setBackgroundColor('white')
    view.zoomTo()
    print(
        f"Counterions added: {ion_counts['NA+']} NA+ (purple), "
        f"{ion_counts['CL-']} CL- (green)."
    )
    view.show()
    return view

def update_and_check_topology(peptide, n_peptides, bead_table, top_file, structure_file):
    """Synchronize a Martini topology with the final solvated structure."""
    top_file = Path(top_file)
    structure_file = Path(structure_file)

    gro_lines = structure_file.read_text().splitlines()
    final_counts = {
        name: sum(line[5:10].strip() == name for line in gro_lines[2:-1])
        for name in ('W', 'NA+', 'CL-')
    }
    ion_count = final_counts['NA+'] + final_counts['CL-']
    topology_before = top_file.read_text()

    print(f'Topology before changes ({top_file.name}):\n')
    print(topology_before)

    topology_after = re.sub(
        rf'(?m)^{re.escape(peptide)}\s+\d+\s*$',
        f'{peptide:<20} {n_peptides}',
        topology_before,
    )

    if ion_count:
        # 1. Include the Martini 2 ion definitions below the main force-field include.
        main_include = '#include "martini_v2.2.itp"'
        ion_include = '#include "martini_v2.0_ions.itp"'
        assert main_include in topology_after, (
            f'Main Martini include not found in {top_file.name}'
        )
        if ion_include not in topology_after:
            topology_after = topology_after.replace(
                main_include, main_include + '\n' + ion_include, 1
            )

        # 2. Use the solvent and ion counts from the final .gro file.
        topology_after = re.sub(
            r'(?m)^(W|NA\+|CL-)\s+\d+\s*$\n?', '', topology_after
        )
        molecule_lines = [f'W                   {final_counts["W"]}']
        for ion in ('NA+', 'CL-'):
            if final_counts[ion]:
                molecule_lines.append(f'{ion:<20}{final_counts[ion]}')
        topology_after = (
            topology_after.rstrip() + '\n' + '\n'.join(molecule_lines) + '\n'
        )

    if topology_after != topology_before:
        top_file.write_text(topology_after)
        print(f'Updated {top_file.name}.')
    else:
        print(f'{top_file.name} already matches the final structure.')

    print(f'\nTopology after changes ({top_file.name}):\n')
    print(topology_after)

    # Check the final coordinate and topology files.
    expected_beads = n_peptides * len(bead_table) + sum(final_counts.values())
    assert int(gro_lines[1]) == expected_beads
    assert f'{peptide:<20} {n_peptides}' in topology_after
    assert f'W                   {final_counts["W"]}' in topology_after
    if ion_count:
        assert ion_include in topology_after
        assert topology_after.index(ion_include) > topology_after.index(main_include)
    for ion in ('NA+', 'CL-'):
        if final_counts[ion]:
            assert f'{ion:<20}{final_counts[ion]}' in topology_after

    print(f'{structure_file.name}: {int(gro_lines[1])} coarse-grained beads')
    print(f'Box vectors (nm): {gro_lines[-1].strip()}')
    print(
        f'Molecule counts: W={final_counts["W"]}, '
        f'NA+={final_counts["NA+"]}, CL-={final_counts["CL-"]}'
    )
    return final_counts

def setup_all_tripeptides(cg_dir, python2, script_name ):
    """Run setup_tripeptides.sh and print every updated topology file."""
    cg_dir = Path(cg_dir)
    python2 = Path(python2)
    setup_script = cg_dir / script_name

    assert setup_script.is_file(), f'Script not found: {setup_script}'
    assert python2.is_file(), f'Python 2.7 interpreter not found: {python2}'

    batch_env = os.environ.copy()
    batch_env['PATH'] = f'{python2.parent}:{batch_env["PATH"]}'

    print(f'Running {setup_script.name} with {python2}')
    subprocess.run(
        ['bash', '-e', setup_script.name],
        cwd=cg_dir,
        env=batch_env,
        check=True,
    )

    updated_topology_files = sorted(cg_dir.glob('TYR-*-TYR.top'))
    assert updated_topology_files, f'No updated topology files found in {cg_dir}'

    print(f'\nUpdated topology files ({len(updated_topology_files)}):')
    for topology_file in updated_topology_files:
        print('\n' + '=' * 80)
        print(topology_file.name)
        print('=' * 80)
        print(topology_file.read_text().rstrip())

    return updated_topology_files


def plot_minimization_energy(peptide, simulation_dir, minimization_name=None):
    """Extract and plot the potential energy from a GROMACS minimization."""
    simulation_dir = Path(simulation_dir)
    minimization_name = minimization_name or f'{peptide}_min'

    min_edr_file = simulation_dir / f'{minimization_name}.edr'
    min_energy_file = simulation_dir / f'{minimization_name}_potential.xvg'
    assert min_edr_file.is_file(), f'Energy file not found: {min_edr_file}'

    command = [
        'gmx', 'energy',
        '-f', min_edr_file.name,
        '-o', min_energy_file.name,
    ]
    print('Running:', ' '.join(command))
    subprocess.run(
        command,
        input='Potential\n',
        text=True,
        cwd=simulation_dir,
        check=True,
    )

    x_values = []
    potential_energy = []
    x_label = 'Minimization step'

    for line in min_energy_file.read_text().splitlines():
        if line.startswith('@ xaxis label'):
            x_label = line.split('"')[1]
        elif line and line[0] not in '#@&':
            x_value, energy = map(float, line.split()[:2])
            x_values.append(x_value)
            potential_energy.append(energy)

    assert potential_energy, f'No potential-energy values found in {min_energy_file}'

    initial_energy = potential_energy[0]
    final_energy = potential_energy[-1]
    energy_decrease = initial_energy - final_energy

    plt.figure(figsize=(8, 5))
    plt.plot(x_values, potential_energy, color='tab:blue', linewidth=2)
    plt.xlabel(x_label)
    plt.ylabel(r'Potential energy (kJ mol$^{-1}$)')
    plt.title(f'Energy minimization of {peptide}')
    plt.grid(alpha=0.25)
    plt.tight_layout()
    plt.show()

    print(f'Initial potential energy: {initial_energy:,.1f} kJ/mol')
    print(f'Final potential energy:   {final_energy:,.1f} kJ/mol')
    print(f'Energy decrease:          {energy_decrease:,.1f} kJ/mol')

    return {
        'initial_energy': initial_energy,
        'final_energy': final_energy,
        'energy_decrease': energy_decrease,
        'energy_file': min_energy_file,
    }


def show_simulation_trajectory(
    peptide,
    simulation_dir,
    bead_table,
    simulation_name=None,
    frame_stride=1,
    show_water=False,
    show_ions=True,
    frame_interval=100,
    width=900,
    height=600,
):
    """Display a GROMACS trajectory with VMD-like playback and controls."""
    simulation_dir = Path(simulation_dir)
    simulation_name = simulation_name or f'{peptide}_eq'
    frame_stride = int(frame_stride)
    assert frame_stride > 0, 'frame_stride must be a positive integer.'

    tpr_file = simulation_dir / f'{simulation_name}.tpr'
    trajectory_file = simulation_dir / f'{simulation_name}.xtc'
    viewer_file = simulation_dir / f'{simulation_name}_system.pdb'

    assert tpr_file.is_file(), f'Run-input file not found: {tpr_file}'
    assert trajectory_file.is_file(), f'Trajectory file not found: {trajectory_file}'

    command = [
        'gmx', 'trjconv',
        '-s', tpr_file.name,
        '-f', trajectory_file.name,
        '-o', viewer_file.name,
        '-pbc', 'mol',
        '-center',
        '-ur', 'compact',
        '-skip', str(frame_stride),
    ]
    print('Running:', ' '.join(command), flush=True)
    subprocess.run(
        command,
        input='Protein\nSystem\n',
        text=True,
        cwd=simulation_dir,
        check=True,
    )

    trajectory_text = viewer_file.read_text()
    number_of_frames = trajectory_text.count('MODEL') or 1
    first_frame = trajectory_text.split('ENDMDL', 1)[0]
    atom_lines = [
        line for line in first_frame.splitlines()
        if line.startswith(('ATOM', 'HETATM'))
    ]
    atom_names = [line[12:16].strip() for line in atom_lines]
    water_count = atom_names.count('W')
    ion_names = ('NA+', 'CL-', 'NA', 'CL')
    ion_count = sum(name in ion_names for name in atom_names)

    print(f'Loaded {number_of_frames} trajectory frames for {peptide}.')
    print(f'Each frame contains {water_count} water beads and {ion_count} ion beads.')

    viewer = py3Dmol.view(width=width, height=height)
    viewer.addModelsAsFrames(trajectory_text, 'pdb')
    viewer.setStyle({}, {})

    class_colors = {
        'charged': 'red',
        'polar': 'orange',
        'intermediate': 'blue',
        'apolar': 'gray',
    }
    bead_styles = {}
    for _, bead in bead_table.iterrows():
        residue_name = str(bead['residue']).split()[0]
        bead_name = str(bead['bead'])
        bead_class = str(bead['class']).lower()
        bead_styles[(residue_name, bead_name)] = (
            bead_class,
            _peptide_bead_radius(bead['Martini type']),
        )

    for (residue_name, bead_name), (bead_class, radius) in bead_styles.items():
        viewer.setStyle(
            {'resn': residue_name, 'atom': bead_name},
            {'sphere': {
                'radius': radius,
                'color': class_colors.get(bead_class, 'gray'),
            }},
        )

    crystal_line = next(
        (line for line in first_frame.splitlines() if line.startswith('CRYST1')),
        None,
    )
    if crystal_line:
        box_x = float(crystal_line[6:15])
        box_y = float(crystal_line[15:24])
        box_z = float(crystal_line[24:33])

        # Draw only the 12 outer edges; addBox wireframe triangulates each face.
        box_corners = [
            {'x': 0.0,   'y': 0.0,   'z': 0.0},
            {'x': box_x, 'y': 0.0,   'z': 0.0},
            {'x': 0.0,   'y': box_y, 'z': 0.0},
            {'x': box_x, 'y': box_y, 'z': 0.0},
            {'x': 0.0,   'y': 0.0,   'z': box_z},
            {'x': box_x, 'y': 0.0,   'z': box_z},
            {'x': 0.0,   'y': box_y, 'z': box_z},
            {'x': box_x, 'y': box_y, 'z': box_z},
        ]
        box_edges = [
            (0, 1), (0, 2), (0, 4),
            (1, 3), (1, 5), (2, 3),
            (2, 6), (3, 7), (4, 5),
            (4, 6), (5, 7), (6, 7),
        ]
        for start_index, end_index in box_edges:
            viewer.addLine({
                'start': box_corners[start_index],
                'end': box_corners[end_index],
                'color': 'black',
                'linewidth': 2.0,
            })

    water_checkbox = widgets.Checkbox(
        value=bool(show_water),
        description='Show water beads',
        indent=False,
    )
    ion_checkbox = widgets.Checkbox(
        value=bool(show_ions and ion_count),
        description=(
            f'Show ion beads ({ion_count})'
            if ion_count else 'Show ion beads (none present)'
        ),
        indent=False,
        disabled=(ion_count == 0),
    )

    def update_solvent_visibility(change=None):
        water_style = (
            {'sphere': {
                'radius': WATER_BEAD_RADIUS_ANGSTROM,
                'color': 'cyan',
                'opacity': 0.35,
            }}
            if water_checkbox.value else {}
        )
        viewer.setStyle({'atom': 'W'}, water_style)

        for ion_name in ion_names:
            ion_style = {}
            if ion_checkbox.value:
                ion_style = {
                    'sphere': {
                        'scale': 0.55,
                        'color': 'purple' if ion_name.startswith('NA') else 'green',
                    }
                }
            viewer.setStyle({'atom': ion_name}, ion_style)
        if change is not None:
            viewer.update()

    water_checkbox.observe(update_solvent_visibility, names='value')
    ion_checkbox.observe(update_solvent_visibility, names='value')
    update_solvent_visibility()

    frame_slider = widgets.IntSlider(
        value=0,
        min=0,
        max=number_of_frames - 1,
        step=1,
        description='Frame',
        continuous_update=True,
        readout=True,
        layout=widgets.Layout(width='650px'),
    )
    frame_status = widgets.HTML(
        value=f'<b>Frame 0 of {number_of_frames - 1}</b>',
        layout=widgets.Layout(
            min_width='130px',
            margin='0 0 0 8px',
        ),
    )
    play_controller = widgets.Play(
        value=0,
        min=0,
        max=number_of_frames - 1,
        step=1,
        interval=frame_interval,
        repeat=False,
        show_repeat=True,
    )
    play_controller.add_class('martini-play-controller')
    play_controller.layout = widgets.Layout(
        width='184px',
        min_width='184px',
    )
    widgets.jslink(
        (play_controller, 'value'),
        (frame_slider, 'value'),
    )

    playback_css = widgets.HTML(
        value='''
        <style>
        .martini-play-controller {
            display: flex !important;
            align-items: center !important;
            width: 184px !important;
            min-width: 184px !important;
            height: 36px !important;
            overflow: visible !important;
        }
        .martini-play-controller button {
            display: inline-flex !important;
            align-items: center !important;
            justify-content: center !important;
            flex: 0 0 42px !important;
            min-width: 42px !important;
            width: 42px !important;
            height: 36px !important;
            margin: 0 2px !important;
            padding: 0 !important;
            border: 1px solid #5f6368 !important;
            color: white !important;
            background: #3367d6 !important;
            font-family: Arial, sans-serif !important;
            font-size: 0 !important;
            line-height: 36px !important;
            vertical-align: middle !important;
            position: relative !important;
        }
        .martini-play-controller button:hover {
            background: #2851a3 !important;
        }
        .martini-play-controller button i {
            display: none !important;
        }
        .martini-play-controller button::after {
            display: flex !important;
            align-items: center !important;
            justify-content: center !important;
            width: 100% !important;
            height: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
            color: white !important;
            font-family: Arial, sans-serif !important;
            font-size: 19px !important;
            font-style: normal !important;
            line-height: 1 !important;
            position: absolute !important;
            inset: 0 !important;
        }
        .martini-play-controller button:nth-of-type(1)::after {
            content: '▶' !important;
        }
        .martini-play-controller button:nth-of-type(2)::after {
            content: '⏸' !important;
        }
        .martini-play-controller button:nth-of-type(3)::after {
            content: '■' !important;
        }
        .martini-play-controller button:nth-of-type(4)::after {
            content: '↻' !important;
        }
        </style>
        '''
    )

    def update_frame(change):
        if change['name'] == 'value':
            viewer.setFrame(change['new'])
            viewer.update()
            frame_status.value = (
                f'<b>Frame {change["new"]} of {number_of_frames - 1}</b>'
            )

    frame_slider.observe(update_frame, names='value')

    viewer.setBackgroundColor('white')
    viewer.setFrame(0)
    viewer.zoomTo()

    display(playback_css)
    display(widgets.HBox(
        [
            widgets.HTML(
                '<b>Playback:</b>',
                layout=widgets.Layout(margin='0 8px 0 0'),
            ),
            play_controller,
            frame_status,
        ],
        layout=widgets.Layout(
            align_items='center',
            overflow='visible',
        ),
    ))
    display(frame_slider)
    display(widgets.HBox([water_checkbox, ion_checkbox]))
    viewer.show()
    print('Drag to rotate, scroll to zoom, or use the labeled playback controls.')
    print('Martini colors: charged=red, polar=orange, intermediate=blue, apolar=gray.')
    print('Solvent colors: water=cyan, NA+=purple, CL-=green.')

    return {
        'viewer': viewer,
        'play_controller': play_controller,
        'frame_slider': frame_slider,
        'water_checkbox': water_checkbox,
        'ion_checkbox': ion_checkbox,
        'number_of_frames': number_of_frames,
        'viewer_file': viewer_file,
    }

