"""OpenMM helpers for the peptide self-assembly notebook."""

from pathlib import Path
from typing import Union

import py3Dmol

from openmm import Platform, VerletIntegrator, unit
from openmm.app import ForceField, NoCutoff, PDBFile, Simulation


def minimize_peptides(coord_dir: Union[str, Path]) -> list[Path]:
    """Energy-minimize the 20 VMD-built Tyr-X-Tyr peptide structures.

    Each ``TYR-*-TYR_aa.pdb`` file in ``coord_dir`` is minimized on the
    OpenMM CPU platform with CHARMM36 and OBC2 implicit solvent. The minimized
    coordinates overwrite the input PDB file, matching the notebook workflow.

    Parameters
    ----------
    coord_dir
        Directory containing the PDB files generated by ``make_peptides.sh``.

    Returns
    -------
    list[pathlib.Path]
        The 20 minimized PDB paths, sorted by filename.
    """
    coord_dir = Path(coord_dir)
    generated = sorted(coord_dir.glob("TYR-*-TYR_aa.pdb"))
    assert len(generated) == 20, "Run make_peptides.sh before minimizing."

    forcefield = ForceField("charmm36.xml", "implicit/obc2.xml")
    platform = Platform.getPlatformByName("CPU")

    for pdb_file in generated:
        pdb = PDBFile(str(pdb_file))
        system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff)
        integrator = VerletIntegrator(0.001 * unit.picoseconds)
        simulation = Simulation(pdb.topology, system, integrator, platform)
        simulation.context.setPositions(pdb.positions)

        before = simulation.context.getState(getEnergy=True).getPotentialEnergy()
        simulation.minimizeEnergy(
            tolerance=10 * unit.kilojoule_per_mole / unit.nanometer,
            maxIterations=500,
        )
        state = simulation.context.getState(getEnergy=True, getPositions=True)
        after = state.getPotentialEnergy()

        with pdb_file.open("w") as output:
            PDBFile.writeFile(
                pdb.topology,
                state.getPositions(),
                output,
                keepIds=True,
            )

        before_kj_mol = before.value_in_unit(unit.kilojoule_per_mole)
        after_kj_mol = after.value_in_unit(unit.kilojoule_per_mole)
        print(f"{pdb_file.name}: {before_kj_mol:.1f} kJ/mol -> "
              f"{after_kj_mol:.1f} kJ/mol")

    return generated


def show_peptide(
    peptide: str,
    style: str,
    coord_dir: Union[str, Path],
) -> None:
    """Display a minimized peptide in an interactive py3Dmol viewer."""
    pdb_file = Path(coord_dir) / f"{peptide}_aa.pdb"
    if not pdb_file.is_file():
        raise FileNotFoundError(pdb_file)

    styles = {
        "Stick": {"stick": {"colorscheme": "Jmol"}},
        "Ball and stick": {
            "stick": {"colorscheme": "Jmol"},
            "sphere": {"scale": 0.3, "colorscheme": "Jmol"},
        },
        "Sphere": {"sphere": {"colorscheme": "Jmol"}},
    }
    if style not in styles:
        raise ValueError(f"Unknown style: {style!r}. Choose from {tuple(styles)}.")

    view = py3Dmol.view(width=800, height=500)
    view.addModel(pdb_file.read_text(), "pdb")
    view.setStyle({}, styles[style])
    view.setBackgroundColor("white")
    view.zoomTo()
    view.show()




def show_peptide_widget(generated, coord_dir: Union[str, Path]):
    """Create peptide and rendering-style controls for ``show_peptide``."""
    from ipywidgets import Dropdown, fixed, interact

    peptide_names = [
        path.name.removesuffix("_aa.pdb") for path in generated
    ]
    if not peptide_names:
        raise ValueError("No generated peptide files were provided.")

    default_peptide = (
        "TYR-VAL-TYR" if "TYR-VAL-TYR" in peptide_names else peptide_names[0]
    )

    return interact(
        show_peptide,
        peptide=Dropdown(
            options=peptide_names,
            value=default_peptide,
            description="Peptide:",
        ),
        style=Dropdown(
            options=["Stick", "Ball and stick", "Sphere"],
            value="Ball and stick",
            description="Style:",
        ),
        coord_dir=fixed(Path(coord_dir)),
    )
