"""OpenMM helpers for the peptide self-assembly notebook."""

from pathlib import Path
from typing import Union

import pandas as pd
from IPython.display import HTML, display


import py3Dmol

from openmm import Platform, VerletIntegrator, unit
from openmm.app import ForceField, NoCutoff, PDBFile, Simulation


def minimize_peptides(coord_dir: Union[str, Path]) -> list[Path]:
    """Energy-minimize the 20 VMD-built Tyr-X-Tyr peptide structures.

    Each ``TYR-*-TYR_aa.pdb`` file in ``coord_dir`` is minimized on the
    OpenMM CPU platform with CHARMM36 and OBC2 implicit solvent. The minimized
    coordinates overwrite the input PDB file, matching the notebook workflow.

    Parameters
    ----------
    coord_dir
        Directory containing the PDB files generated by ``make_peptides.sh``.

    Returns
    -------
    list[pathlib.Path]
        The 20 minimized PDB paths, sorted by filename.
    """
    coord_dir = Path(coord_dir)
    generated = sorted(coord_dir.glob("TYR-*-TYR_aa.pdb"))
    assert len(generated) == 20, "Run make_peptides.sh before minimizing."

    forcefield = ForceField("charmm36.xml", "implicit/obc2.xml")
    platform = Platform.getPlatformByName("CPU")

    for pdb_file in generated:
        pdb = PDBFile(str(pdb_file))
        system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff)
        integrator = VerletIntegrator(0.001 * unit.picoseconds)
        simulation = Simulation(pdb.topology, system, integrator, platform)
        simulation.context.setPositions(pdb.positions)

        before = simulation.context.getState(getEnergy=True).getPotentialEnergy()
        simulation.minimizeEnergy(
            tolerance=10 * unit.kilojoule_per_mole / unit.nanometer,
            maxIterations=500,
        )
        state = simulation.context.getState(getEnergy=True, getPositions=True)
        after = state.getPotentialEnergy()

        with pdb_file.open("w") as output:
            PDBFile.writeFile(
                pdb.topology,
                state.getPositions(),
                output,
                keepIds=True,
            )

        before_kj_mol = before.value_in_unit(unit.kilojoule_per_mole)
        after_kj_mol = after.value_in_unit(unit.kilojoule_per_mole)
        print(f"{pdb_file.name}: {before_kj_mol:.1f} kJ/mol -> "
              f"{after_kj_mol:.1f} kJ/mol")

    return generated


def show_peptide(
    peptide: str,
    style: str,
    coord_dir: Union[str, Path],
) -> None:
    """Display a minimized peptide in an interactive py3Dmol viewer."""
    pdb_file = Path(coord_dir) / f"{peptide}_aa.pdb"
    if not pdb_file.is_file():
        raise FileNotFoundError(pdb_file)

    styles = {
        "Stick": {"stick": {"colorscheme": "Jmol"}},
        "Ball and stick": {
            "stick": {"colorscheme": "Jmol"},
            "sphere": {"scale": 0.3, "colorscheme": "Jmol"},
        },
        "Sphere": {"sphere": {"colorscheme": "Jmol"}},
    }
    if style not in styles:
        raise ValueError(f"Unknown style: {style!r}. Choose from {tuple(styles)}.")

    view = py3Dmol.view(width=800, height=500)
    view.addModel(pdb_file.read_text(), "pdb")
    view.setStyle({}, styles[style])
    view.setBackgroundColor("white")
    view.zoomTo()
    view.show()




def show_peptide_widget(generated, coord_dir: Union[str, Path]):
    """Create peptide and rendering-style controls for ``show_peptide``."""
    from ipywidgets import Dropdown, fixed, interact

    peptide_names = [
        path.name.removesuffix("_aa.pdb") for path in generated
    ]
    if not peptide_names:
        raise ValueError("No generated peptide files were provided.")

    default_peptide = (
        "TYR-VAL-TYR" if "TYR-VAL-TYR" in peptide_names else peptide_names[0]
    )

    return interact(
        show_peptide,
        peptide=Dropdown(
            options=peptide_names,
            value=default_peptide,
            description="Peptide:",
        ),
        style=Dropdown(
            options=["Stick", "Ball and stick", "Sphere"],
            value="Ball and stick",
            description="Style:",
        ),
        coord_dir=fixed(Path(coord_dir)),
    )



def show_peptide_comparison(peptide, cg_dir):
    """Compare an all-atom peptide with its Martini representation."""

    cg_dir = Path(cg_dir)

    aa_file = (
        cg_dir.parent
        / "2_Creating_coordinates"
        / f"{peptide}_aa.pdb"
    )
    cg_file = cg_dir / f"{peptide}.pdb"
    itp_file = cg_dir / f"{peptide}.itp"

    assert aa_file.is_file(), f"File not found: {aa_file}"
    assert cg_file.is_file(), f"File not found: {cg_file}"
    assert itp_file.is_file(), f"File not found: {itp_file}"

    itp_text = itp_file.read_text()

    # Read the coarse-grained coordinates from the PDB file.
    coordinates = {}

    for line in cg_file.read_text().splitlines():
        if line.startswith(("ATOM  ", "HETATM")):
            serial = int(line[6:11])

            coordinates[serial] = tuple(
                float(line[start:end])
                for start, end in (
                    (30, 38),
                    (38, 46),
                    (46, 54),
                )
            )

    family_names = {
        "Q": "charged",
        "P": "polar",
        "N": "intermediate",
        "C": "apolar",
    }

    family_colors = {
        "Q": "#D62728",
        "P": "#FF7F0E",
        "N": "#4169E1",
        "C": "#8A8A8A",
    }

    def bead_family(bead_type):
        core = bead_type[1:] if bead_type.startswith("S") else bead_type
        core = core[1:] if core.startswith("A") else core
        return core[0]

    def polarity_label(bead_type):
        core = bead_type[1:] if bead_type.startswith("S") else bead_type
        core = core[1:] if core.startswith("A") else core
        subtype = core[1:]

        h_bond = {
            "da": "donor + acceptor",
            "d": "donor",
            "a": "acceptor",
            "0": "none",
        }

        return h_bond.get(subtype, f"level {subtype}")

    # Read the bead information and connectivity from the topology.
    rows = []
    bond_pairs = []
    section = None

    for line in itp_text.splitlines():
        stripped = line.strip()

        if stripped.startswith("["):
            section = stripped.strip("[] ").lower()
            continue

        fields = line.split(";", 1)[0].split()

        if section == "atoms" and fields and fields[0].isdigit():
            index = int(fields[0])
            bead_type = fields[1]
            family = bead_family(bead_type)

            rows.append({
                "index": index,
                "residue": f"{fields[3]} {fields[2]}",
                "bead": fields[4],
                "Martini type": bead_type,
                "class": family_names[family],
                "polarity / H-bonding": polarity_label(bead_type),
                "charge (e)": float(fields[6]),
            })

        elif (
            section in ("bonds", "constraints")
            and len(fields) >= 2
            and fields[0].isdigit()
        ):
            bond_pairs.append((
                int(fields[0]),
                int(fields[1]),
            ))

    bead_table = (
        pd.DataFrame(rows)
        .sort_values("index")
        .reset_index(drop=True)
    )

    # Display only the requested columns.
    table_columns = [
        "residue",
        "bead",
        "Martini type",
        "class",
        "polarity / H-bonding",
    ]

    display(bead_table[table_columns].style.hide(axis="index"))

    print(
        "Color key: charged=red, polar=orange, "
        "intermediate=blue, apolar=gray."
    )
    print(
        "Connectivity:",
        ", ".join(f"{first}-{second}" for first, second in bond_pairs),
    )

    # Add titles above the molecular viewers.
    display(HTML(
        f"""
        <div style="display:flex; width:1000px; text-align:center">
            <b style="width:50%">All-atom: {peptide}</b>
            <b style="width:50%">Martini 2.2 beads</b>
        </div>
        """
    ))

    # Create two linked molecular viewers.
    view = py3Dmol.view(
        width=1000,
        height=520,
        viewergrid=(1, 2),
        linked=True,
    )

    # All-atom structure.
    view.addModel(
        aa_file.read_text(),
        "pdb",
        viewer=(0, 0),
    )

    view.setStyle(
        {},
        {
            "stick": {"colorscheme": "Jmol"},
            "sphere": {
                "scale": 0.25,
                "colorscheme": "Jmol",
            },
        },
        viewer=(0, 0),
    )

    # Martini coarse-grained structure.
    view.addModel(
        cg_file.read_text(),
        "pdb",
        viewer=(0, 1),
    )

    for row in rows:
        serial = row["index"]
        bead_type = row["Martini type"]
        color = family_colors[bead_family(bead_type)]

        view.setStyle(
            {"serial": serial},
            {
                "sphere": {
                    "color": color,
                    "radius": 1.1,
                }
            },
            viewer=(0, 1),
        )

        x, y, z = coordinates[serial]

        view.addLabel(
            (
                f"{row['bead']} | {bead_type} | "
                f"q={row['charge (e)']:+.0f}"
            ),
            {
                "position": {"x": x, "y": y, "z": z},
                "fontSize": 11,
                "fontColor": "black",
                "backgroundColor": "white",
                "backgroundOpacity": 0.75,
                "inFront": True,
            },
            viewer=(0, 1),
        )

    # Draw connections between Martini beads.
    for first, second in bond_pairs:
        start = coordinates[first]
        end = coordinates[second]

        view.addCylinder(
            {
                "start": dict(zip(("x", "y", "z"), start)),
                "end": dict(zip(("x", "y", "z"), end)),
                "radius": 0.12,
                "color": "#555555",
                "opacity": 0.75,
            },
            viewer=(0, 1),
        )

    view.setBackgroundColor("white")
    view.zoomTo()
    view.show()

    return bead_table